# Generic minimal RX888-wsprdaemon config - TEMPLATE
# Copy this file to /etc/radio/radiod@<YOUR_INSTANCE_NAME>.conf and edit as needed.

[global]
hardware = rx888 # use built-in rx888 driver, configured in [rx888]
status = YOUR_STATUS_HOST.local       # DNS name for receiver status and commands (e.g., myradio-status.local)
#data = YOUR_DATA_HOST.local
samprate = 24000        # default output sample rate
mode = usb 		# default receive mode
# rest are defaults
ttl = 1
#ttl = 0                 # Too many WD sites don't have IGMP aware ethernet swtiches, so don't send radiod multicast packets out the ethernet port.
fft-threads = 1
iface = YOUR_INTERFACE_NAME # e.g., eth0, enp1s0

[rx888]
device = "rx888" # required so it won't be seen as a demod section
description = "YOUR_CALLSIGN @ YOUR_GRID YOUR_ANTENNA" # good to put callsign and antenna description in here
# gain = 0 # dB
# rest are defaults
samprate = 129600000     # Hz
#samprate =   64800000     # 128 Msps will eventual burn out the stock RX888 Mk II, and this 64 Msps frees much CPU on older CPUs

[WWV-IQ]
encoding=float
gain=0
agc=0
disable=no
freq = "2m500000 5m000000 10m000000 15m000000 20m000000 25m000000"

[FT8]
disable = yes
data = YOUR_FT8_PCM_HOST.local # e.g., myradio-ft8-pcm.local
mode = usb
freq = "1m840000 3m573000 5m357000 7m074000 10m136000 14m074000 18m100000 21m074000 24m915000 28m074000 50m313000"

[FT4]
disable = yes
data = YOUR_FT4_PCM_HOST.local # e.g., myradio-ft4-pcm.local
mode = usb
freq = "3m575000 7m047500 10m140000 14m080000 18m104000 21m140000 24m919000 28m180000 50m318000"

[WSPR]
# Bottom of 200 Hz WSPR segments on each band. Center is 1500 Hz higher
# sample rate must be 12 kHz as required by wsprd
disable = yes
encoding=float
data = YOUR_WSPR_PCM_HOST.local # e.g., myradio-wspr-pcm.local
agc=0
gain=0
samprate = 24000
mode = usb
low=1300
high=1700
freq = "136k000 474k200 1m836600 3m568600 3m592600 5m287200 5m364700 7m038600 10m138700 13m553900 14m095600 18m104600 21m094600 24m924600 28m124600 50m293000"

[HF MANUAL]
data = YOUR_HF_PCM_HOST.local # e.g., myradio-hf-pcm.local
freq = 0
